server:
  port: 9002
  ssl:
    key-store:          "classpath:keystore.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"
    key-alias:          "tomcat"

spring:
  security:
    oauth2:
      client:
        registration:
          bitbucket:
            provider:                     "bitbucket"
            client-name:                  "Bitbucket"
            client-id:                    "[env]"
            client-secret:                "[env]"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - account
        provider: 
          bitbucket:
            authorization-uri:   "https://bitbucket.org/site/oauth2/authorize"
            token-uri:           "https://bitbucket.org/site/oauth2/access_token"
            user-info-uri:       "https://api.bitbucket.org/2.0/user"
            user-name-attribute: "account_id"

logging:
  level:
    com.example:                                 "DEBUG"
    org.springframework.web.client.RestTemplate: "DEBUG"  